config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount ActionCable.server => "/cable"
  devise_for :users
  root to: 'questions#index'
  resources :stories, except: :destroy
  get 'wiki', to: "pages#wiki", as: :wiki
  get 'welcome', to: "pages#welcome", as: :welcome
  get 'chefsftvi', to: "pages#chefsftvi", as: :chefsftvi
  get 'live_index', to: "questions#live_index", as: :live_index
   get 'archives', to: "questions#archives", as: :archives
  resources :questions do
     member do
    put "like", to: "questions#upvote"
    put "dislike", to: "questions#downvote"
    put "archive", to: "questions#archive"
  end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
    belongs_to :user
    validates :title, uniqueness: true, presence: true
    acts_as_votable
    # after_create :broadcast_question
    # after_update :broadcast_question

# def broadcast_question
#     ActionCable.server.broadcast("dynamic_index", {
#       question_partial: ApplicationController.renderer.render(
#               partial: "questions/question",
#               locals: { question: self, user_is_question_author: false }
#         ),
#       })
# end

end

app/models/story.rb
class Story < ApplicationRecord
    paginates_per 75
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :questions
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # [...]
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :index, :show, :edit, :new, :update, :live_index]

  def home
  end

  def wiki
  end

  def welcome
  end

  def chefsftvi
  end

  def index
  end

  def show
  end

  def edit
  end

  def new
  end

  def update
  end


end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]


  def new
    @question = Question.new
    authorize @question

  end

  def index
    @questions = policy_scope(Question.where(asked: false))
  end

  def archives
    @questions = Question.where(["cached_votes_up > ? and asked = ?", "0", "true"])
    authorize @questions
  end

  def live_index
    @questions = Question.where(asked: false)
    authorize @questions
  end

  def show
    authorize @question
  end

  def edit
  end

  def destroy
    @question.destroy
    authorize @question
    ActionCable.server.broadcast("dynamic_index", {
      question: @question,
      test: "test",
      question_partial: ApplicationController.renderer.render(
              partial: "questions/question",
              locals: { question: @question, user_is_question_author: false }
        )
      })

    redirect_to(questions_path)

  end

  def create
    @question = current_user.questions.build(question_params)
    @question.save
    authorize @question
    ActionCable.server.broadcast("dynamic_index", {
      question: @question,
      question_partial: ApplicationController.renderer.render(
              partial: "questions/question",
              locals: { question: @question, user_is_question_author: false}
        ),
      })

    redirect_to questions_path
  end

  def update
    @question.update(question_params)
   ActionCable.server.broadcast("dynamic_index", {
      question: @question,
      test: "upvote",
      question_partial: ApplicationController.renderer.render(
              partial: "questions/question",
              locals: { question: @question, user_is_question_author: false }
        ),
      })
    redirect_to(questions_path)

  end

  def upvote
    @question = Question.find(params[:id])
    @question.upvote_by current_user
    authorize @question
    ActionCable.server.broadcast("dynamic_index", {
      test: "upvote",
      question: @question,
      question_partial: ApplicationController.renderer.render(
              partial: "questions/question",
              locals: { question: @question, user_is_question_author: false }
        ),
      })
    redirect_to(questions_path)

  end

  def downvote
    @question = Question.find(params[:id])
    @question.downvote_by current_user
    redirect_to(questions_path)
  end

   def archive
    @question = Question.find(params[:id])
    @question.asked = true
    @question.save
    authorize @question
    redirect_to(questions_path)
  end

 private

  def question_params
    params.require(:question).permit(:title, :description, :end_date, :asked, :votes, :answer)
  end

  def set_question
    @question = Question.find(params[:id])
    authorize @question
  end



end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  def index
    @stories = policy_scope(Story.all).order(firstPublicationDate: :desc)
.page params[:page]

  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>La boîte à question</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= yield :after_js %>
  </body>
</html>

app/views/pages/chefsftvi.html.erb
<div class="container" id="listedocs">
<h1>Nos documents de références</h1>
<h2><a href="https://docs.google.com/forms/d/e/1FAIpQLSe49c96aOv62ZEKOhuLTVHDxC58iRe6IyOpqauFen4vrFv3zg/viewform?usp=sf_link">Qu'est ce qu'un bon titre ?</a></h2>

<h2><a href="https://docs.google.com/document/d/1AkZ7usqbc_nCixA4n6nOaX2Aud8-Cyt1pOVXxe-nwVw/edit?usp=sharing">Quand publier/pusher une story</a>(<a href="https://drive.google.com/file/d/1WBAcRFVhl6Dn7e8PSsJ-2UGgneUKml0T/view?usp=sharing">la prez de Mohamed</a></h2>

<h2><a href="https://docs.google.com/document/d/10YIZDLaOQpiXzU499pVpm8onfjE9s9hj1u6MJRYJ5Fg/edit">Les stories : definitions of done</a></h2>
<h2><a href="https://docs.google.com/forms/d/e/1FAIpQLSeKsye0CO63Yqg1liNFb5G70bbBPvoM6hD9VJ07UHLn9kh49Q/viewform?usp=sf_link">Est-ce que mon papier mérite le slug "enquête" ?</a></h2>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/welcome.html.erb
welcome docs

app/views/pages/wiki.html.erb
Futre ref docs

app/views/questions/_question.erb
  <%= link_to question_path(question), method: :get do %>
  <div class="product" id="<%= 'question_' + question.id.to_s %>">
    <div class="product-upvote">
      <%= link_to like_question_path(question), method: :put do %>
      <i class="fa fa-arrow-circle-up"></i><% end %>
        <div class='product-count'><%= question.get_upvotes.size %></div>
    </div>
    <div class="product-body">
      <h3><%= link_to "#{question.title}", question_path(question), class:"link-question" %></h3>
      <p><%= question.description %></p>
    </div>
    <div class="product-controls" id ="action-button">
      <% if user_is_question_author == true %>
      <%= link_to "", question, method: :delete, class:"fa fa-trash" %>
      <%= link_to "", edit_question_path(question), class:"fa fa-pencil" %>
      <%= link_to "", archive_question_path(question), method: :put, class:"fa fa-check" %>
      <% end %>
    </div>
  </div>
  <div class="answer">
    <% if question.answer != nil  %>
      <%= link_to "voir la réponse", question_path(question), class:"link-question" %>
    <% end  %>
  </div>

<% end %>

app/views/questions/archives.html.erb
<div class="container">
  <div class="row" style="padding-top: 30px;">
    <div class="col-xs-10 col-xs-offset-1 col-sm-4 col-sm-offset-4">
      <%= link_to "Poser une nouvelle question", new_question_path, class:"btn revote" %>
      <%# end %>
    </div>
  </div>
  <% if @questions != nil %>
    <div class="row">
      <div class="col-xs-12" id="listequestion" style="padding-top: 20px;">
        <% @questions.order(updated_at: :desc).each do |question|  %>
        <%= render "question", question: question, user_is_question_author: question.user == current_user || current_user.admin? %>
        <% end  %>
      </div>
    </div>
      <%= link_to "Retourner aux questions", questions_path, class:"btn revote" %>
  </div>
<% end  %>

app/views/questions/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
      <div class="form-question">
        <h2>Modifier votre question</h2>
        <%= simple_form_for [@question], :method => :patch do |f| %>
          <%= f.input :title, label: "Intitulé de votre question", placeholder:"Rédigez une question claire et concise" %>
          <%= f.input :description, label:false, placeholder:"Vous pouvez ajouter ici des éléments pour préciser votre question" %>
            <%if current_user.admin? %>
            <%= f.input :answer, label: "Ecrire ici une réponse" %>
            <% end  %>
          <%= f.submit "Publier sa question", class: "btn revote" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/questions/index.html.erb
<div class="container">
  <div class="row" style="padding-top: 30px;">
    <div class="col-xs-10 col-xs-offset-1 col-sm-4 col-sm-offset-4">
      <%= link_to "Poser une nouvelle question", new_question_path, class:"btn revote" %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12" id="listequestion">
      <% @questions.order(cached_votes_up: :desc).each do |question|  %>
      <%= render "question", question: question, user_is_question_author: question.user == current_user || current_user.admin?, user_is_admin: current_user.admin? %>
      <% end  %>
    </div>
  </div>

   <!-- <div class="row" style="padding-top: 30px;">
    <div class="col-xs-10 col-xs-offset-1 col-sm-4 col-sm-offset-4">
      <%= link_to "Voir les anciennes questions", archives_path, class:"btn revote" %>
    </div>
  </div>

</div> -->

<% content_for :after_js do %>
  <script>
    App['dynamic_index'] = App.cable.subscriptions.create(
      { channel: 'DynamicIndexChannel'},
      { received: (data) => {
        const questionList = document.getElementById('listequestion');
        const qid = data.question.id;
        const question = document.getElementById("question_" + qid);
        // const controls = question.getElementById("action-button");

        if(data.test !== "upvote") {
        if (data.test === "test"){
          question.remove();
        } else if (question !== null) {
        question.remove();
        questionList.insertAdjacentHTML('afterbegin', data.question_partial);

      } else {
        questionList.insertAdjacentHTML('beforeend', data.question_partial);


      }
        console.log(data)
        }
       }
      }
    )
  </script>
<% end %>

app/views/questions/live_index.html.erb
<div class="container">
  <div class="row" style="padding-top: 30px;">
    <div class="col-xs-10 col-xs-offset-1 col-sm-4 col-sm-offset-4">
      <%# if policy(Question).create? %>

      <%= link_to "Poser une nouvelle question", new_question_path, class:"btn revote" %>
      <%# end %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12" id="listequestion">
      <% @questions.order(cached_votes_up: :desc).each do |question|  %>
      <%= render "question", question: question, user_is_question_author: question.user == current_user || current_user.admin? %>
      <% end  %>
    </div>
  </div>
</div>

<% content_for :after_js do %>
  <script>
    App['dynamic_index'] = App.cable.subscriptions.create(
      { channel: 'DynamicIndexChannel'},
      { received: (data) => {
        const questionList = document.getElementById('listequestion');
        const qid = data.question.id;
        const question = document.getElementById("question_" + qid);
        // const controls = question.getElementById("action-button");

        if (data.test === "test"){
          question.remove();
        } else if (data.test === "upvote"){
          location.reload();
        } else if (question !== null) {
        question.remove();
        questionList.insertAdjacentHTML('afterbegin', data.question_partial);

      } else {
        questionList.insertAdjacentHTML('beforeend', data.question_partial);


      }
        console.log(data)
        }
      }
    )
  </script>
<% end %>

app/views/questions/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
      <div class="form-question">
        <h2>Poser une nouvelle question</h2>
        <%= simple_form_for [@question] do |f| %>
          <%= f.input :title, label: "Intitulé de votre question", placeholder:"Rédigez une question claire et concise" %>
          <%= f.input :description, label:false, placeholder:"Vous pouvez ajouter ici des éléments pour préciser votre question" %>
          <%= f.submit "Publier sa question", class: "btn revote" %>
        <% end %>
    <%= link_to "Retourner aux questions", questions_path, class:"btn revote" %>
      </div>
    </div>
  </div>

</div>

app/views/questions/show.html.erb
<div class="container">
  <div class="product" id="<%= '@question_' + @question.id.to_s %>">
    <div class="product-upvote">
      <%= link_to like_question_path(@question), method: :put do %>
      <i class="fa fa-arrow-circle-up"></i><% end %>
        <div class='product-count'><%= @question.get_upvotes.size %></div>
    </div>
    <div class="product-body">
        <h3><%= @question.title %></h3>
        <p><%= @question.description %></p>
    </div>
  </div>
  <% if @question.answer != nil  %>
    <div class="product" style="margin-top: 28px; margin-bottom: 30px;">
      <div class="product-body">
        <h3>Réponse</h3>
        <p style="color: black; font-weight:normal; margin-top: 25px; margin-bottom: 45px;"><%= @question.answer %></p>
      </div>
    </div>
    <%= link_to "Retourner aux questions", questions_path, class:"btn revote" %>
  </div>
  <% end  %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand", style: "color: transparent;" do %>
   HOME
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Archives", "archives", class: "navbar-wagon-item navbar-wagon-link", style: "color: white;"%>
      <%= link_to "Welcome", "welcome", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Wiki", "wiki", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "https://snjcgt.fr/wp-content/uploads/sites/11/2016/12/franceinfo_logo.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %></li>
                <li>
      <%= link_to "Archives", "archives", class: "navbar-wagon-item navbar-wagon-link", style: "color: white;"%>
      </li>
      </ul>
    </div>
  </div>
</div>

app/views/stories/index.html.erb
<div class="container">

  <div class="row">
    <div class="col-xs-12" id="listequestion">
      <% @stories.each do |story| %>
      <%= link_to "#{story.sharedUrl}", class:"link-question" do %>
      <div class="product">
        <div class="product-upvote hidden-xs">
        <%= image_tag "https://www.francetvinfo.fr/#{story.media}" %>
        </div>

        <div class="product-body">
        <h3><%= link_to "#{story.title}", "#{story.sharedUrl}", class:"link-question"%></h3>
        <p><%= story.description.force_encoding(Encoding::UTF_8) %></p>
        </div>
        <!-- <div class="answer" style="margin: 2px; height: 100%;">
          <p style="color:blue; text-algn: right; margin: 4px"><br><i class="fa fa-facebook"> </i><br><%= story.fb_count %></p>
          <p style="color:grey; text-algn: right; margin: 4px"><br><i class="fa fa-mobile"> <br></i>
            <%= story.mobile_visit %></p>
          <p style="color:grey; text-algn: right; margin: 4px"><br><i class="fa fa-laptop"><br>
          </i><%= story.desktop_visit %><br></p>
        </div> -->
      </div>
      <% end  %>
          <% end  %>
    </div>
    <%= paginate @stories %>
  </div>
</div>